### PR TITLE
Add single HTML language changer, add search box, refactoring

### PR DESCRIPTION
**Pull request by ESchuderer**
Changes are quite extensive, therefore leaving the original docs folder there for now.

### CODE REVIEW

**Comment by hhrhhr** [comment]
Is it possible to reduce the distance at which labels are beginning to gather in clusters?
What about the option to turn off clustering (or only at the last zoom levels)?
So that the commit is not so huge, I'll try to run "git mv" on all resources that moved to new directories.

And most importantly, the search returns only one marker, even if they are many. Try searching for "Small Blue ...", how to see all nine pieces?

**Comment by ESchuderer** [comment]
I'll see what I can do about the search, for the clustering that is possible:

```
var mcg = L.markerClusterGroup({
    chunkedLoading: true,
    disableClusteringAtZoom: 5
});
```

But there are some icons really close together, which are easier to access with the spider feature.

spiderify

**Comment by hhrhhr** [comment]
"use png instead..." is very bad idea.

- "originals" in DDS format occupy 124 MB
- your PNG — 93 Mb
- losless WebP — 63 Mb
- JPG with quality=75 — 8 Mb
- WebP with quality=75 — **<5 Mb**

**Comment by ESchuderer** [comment]
I agree that the bigger filesize might be a problem for people with limited bandwidth or slow connection, maybe could provide a low quality version as well.

Generally I'm no friend of WebP due to it's immense quality loss and lack of browser support.

image_formats

Will add some optimization later on.

**Comment by hhrhhr** [comment]
_>due to it's immense quality loss and lack of browser support._

1. The quality of compression in WebP depends only on the settings. I specifically pointed out the size of all tiles with "lossless" quality.
2. Support of Firefox and IE/Edge is not a priority objective of the current set of scripts to extract game resources.
3. Github is not hosting, so do not put a full set of tiles on it in maximum quality instead of a small test suite for demonstration. Search and clustering do not require tiles in any quality.

And since the pull request went far beyond the "add search box", I close it. One feature is one pull request.

**Comment by ESchuderer** [comment]
I understand, I will provide a PR using the WebP when the map is feature complete, as I do not have the time to develop on two branches or deal with merge conflicts caused by myself.

**Pull request closed without merging**
